import { Card } from "../ui/Card";
import { Copy, CheckCircle } from "lucide-react";
import { Tooltip } from "../ui/Tooltip";

interface DischargePanelProps {
    letter: string | null;
}

export function DischargePanel({ letter }: DischargePanelProps) {
    if (!letter) return null;

    return (
        <Card
            title={
                <div className="flex items-center gap-2">
                    <span>Discharge Summary</span>
                    <Tooltip content="Auto-generated discharge instructions for the client." side="bottom" />
                </div>
            }
            className="border-provet-status-success bg-green-50/50"
            action={<CheckCircle className="w-5 h-5 text-provet-status-success" />}
        >
            <div className="bg-white text-provet-neutral-800 p-6 rounded-xl border border-provet-neutral-200 text-sm font-serif leading-relaxed shadow-sm">
                <pre className="whitespace-pre-wrap font-sans text-sm text-gray-700">{letter}</pre>
                <div className="mt-8 pt-4 border-t border-gray-100 flex justify-between items-center text-xs text-gray-400">
                    <span>Generated by Provet Cloud AI</span>
                    <span>Draft v1.0</span>
                </div>
            </div>
            <div className="mt-4 flex justify-end">
                <button className="flex items-center text-xs font-bold text-provet-purple hover:text-provet-purple-light uppercase tracking-wide px-3 py-2 rounded hover:bg-provet-purple-bg transition-colors">
                    <Copy className="w-3.5 h-3.5 mr-2" /> Copy to Clipboard
                </button>
            </div>
        </Card>
    );
}
